<a href="https://colab.research.google.com/github/CSRU63/COS3109_week2/blob/main/COS3190_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Phyton 


## Hello World

In [ ]:
# Never mind this statement, for compatibility reasons
from __future__ import absolute_import, division, print_function, unicode_literals
print("Hello World")

Hello World


## Function, Conditionals, and Iteration

### Function and contitional

In [ ]:
def HelloWorldXY(x, y):

 if (x < 10):
    print("Hello World, x was < 10")
 elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
 else:
     print("Hello World, x was >= 20")
     
 return x + y

In [ ]:
print(HelloWorldXY(1,2))  

Hello World, x was < 10
3


### Iteration

In [ ]:
 # i=8, 13, 18, 23 (start, stop, step)     
 # i เริ่มต้นเป็น 18 บวกค่าที่ละ 5 ทำจนกว่าจะ  >= 25 ก็หลุด
for i in range(8, 25, 5):    
    print("--- Now running with i: {}".format(i))   # format(i) : การนำค่า i ไปไว้ใน {..} 
    r = HelloWorldXY(i,i)
    print("Result from HelloWorld: {}".format(r))  # r : ค่าที่ retrun x + y มาจาก func โดยส่ง i + i ไปบวก  

    print()

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16

--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26

--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36

--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46



## Various kinds of loops starting at 0 to 2


In [ ]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range (2):
  print(i)

Iterate over the items. `range(2)` is like a list [0,1].
0
1


In [ ]:
print("Iterate over an actual list.")
for i in [0,1]:
  print(i)

Iterate over an actual list.
0
1


In [ ]:
print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

While works
0
1


## Numpy and lists

In [ ]:
sea_creatures = ['shark', 'cuttlefish', 'squid', 'mantis shrimp', 'anemone']

In [ ]:
sea_creatures[0] = 'shark'
sea_creatures[2] = 'squid'
sea_creatures[4] = 'anemone'

In [ ]:
for i in range (5):
  print(sea_creatures[i])

In [ ]:
import numpy as np  # import numpy โดยให้ชื่อเล่นมันว่า np 

a  = np.array( ['Hello ', 'World'])
a  = np.append(a, '!')   # เป็นการ append อักขระ ! เข้าไปในข้อมูลอาร์เรย์ a 
print("Current Array : {}".format(a) )

Current Array : ['Hello ' 'World' '!']


In [ ]:
print("Printing each element")  # พิมพ์ข้อมูลแต่ละตัว
for i in a:
  print(i)

Printing each element
Hello 
World
!


In [ ]:
print("Printing each element and their index")   # พิมพ์ข้อมูลแต่ละตัวโดยใช้ตัวชี้ในการเข้าถึง 
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

In [ ]:
print("-- Showing some basic math on arrays")
b = np.array([0,1,4,3,2])

print("Max: {}".format(np.max(b)))                  
print("Average: {}".format(np.average(b)))      
print("Max index: {}".format(np.argmax(b)))     

print('\n--------------------------------------------')

print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))

-- Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2

--------------------------------------------

You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [ ]:
print("Use numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3,3)
print(c)

Use numpy to create a [3,3] dimension array with random number
[[0.82783169 0.75484844 0.64011378]
 [0.4462478  0.34820768 0.06633917]
 [0.7415105  0.98809383 0.95649424]]


In [ ]:
print("You can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))

ary = np.array(["leo", "mozart"])
print("Shape of ary : {}".format(ary.shape))

You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
Shape of ary : (2,)


## Colab Specifics : to run commands at the VM's terminal, prefix the line with an exclamation point (!)

In [ ]:
!pwd
!ls -l

/content
total 4
drwxr-xr-x 1 root root 4096 Jul 13 13:43 sample_data


In [ ]:
print("Install numpy") # Just for test, numpy is actually preinstalled in all Colab instancs
!pip install numpy

## Exercise

In [ ]:
#1
!pwd
!/root
!ls-l

#2
fruits = ["apple", "banana", "cherry"]

#3
fruits[0] = "kiwi"
for i in fruits:
  print(i)
print("\n-------------------")

#4
import numpy as np
a1 = np.append(fruits, "orange")
for i in a1:
  print(i)
print("\n-------------------")

#5
a1 = np.insert(a1, 1, "Lemon")
for i in a1:
  print(i)
print("\n-------------------")

#6
delete = 2
a1 = np.delete(a1, delete)
for i in a1:
  print(i)
print("\n-------------------")



aa = int(input("enter a : "))
bb = int(input("enter b : "))

#7
if aa > bb :
  print("Hello World")

#8
if aa != bb:
  print("Hello World")

#9
if aa == bb :
  print("Yes")
else:
  print("No")

#10
if aa == bb:
  print("1")
elif aa > bb:
  print("2")
else:
  print("3")

#11
aa = int(input("enter a : "))
bb = int(input("enter b : "))
cc = int(input("enter c : "))
dd = int(input("enter d : "))
if aa == bb and cc == dd:
  print("Hello World")

#12 
if aa == bb or cc == dd:
  print("Hello World")

print("\n-------------------")
#13
for i in range (6):
  print("Loop : #{}".format(i))

print("\n-------------------")

#14
for i in range (3, 14):
  print("Loop : #{}".format(i))
